### ISSUE TITLE
OnlyOffice AppImage Not Loading

### ISSUE THREAD

**Issue by MichaelTunnell** [ONLYOFFICE/appimage-desktopeditors#13] opened 2019-10-10 15:04 UTC
I am getting the following error when I try to launch the AppImage:
`symbol lookup error: /usr/lib/libhogweed.so.5: undefined symbol: __gmpn_cnd_sub_n`

OnlyOffice version = 5.4.1
Operating System = Arch Linux

**Comment by ShockwaveNN** [comment] 2019-10-10 15:21
Duplicate of #3

**Closed by ShockwaveNN** 2019-10-10 15:21 UTC

**Comment by probonopd** [comment] 2019-10-10 16:03
`libgmp.so.10` would need to be removed from the AppImage.
