### ISSUE TITLE
ERRO ONLYOFFICE APPIMAGE ON FEDORA

### ISSUE THREAD

**Issue by PEDROTUBER44** [ONLYOFFICE/appimage-desktopeditors#29] opened 2021-11-12 00:39 UTC
./DesktopEditors: /tmp/.mount_DesktoMnDiEp/usr/bin/libselinux.so.1: no version information available (required by /lib64/libgio-2.0.so.0)
./DesktopEditors: /tmp/.mount_DesktoMnDiEp/usr/bin/libselinux.so.1: no version information available (required by /lib64/libmount.so.1)
./DesktopEditors: symbol lookup error: /lib64/libgio-2.0.so.0: undefined symbol: g_module_open_full

**Comment by ShockwaveNN** [comment] 2021-11-12 06:11
I think this is duplicate of https://github.com/ONLYOFFICE/appimage-desktopeditors/issues/25

**Closed by ShockwaveNN** 2021-11-12 06:11 UTC
